apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: optimizer-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: optimizer-dev.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: optimizer-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: optimizer-dashboard
                port:
                  number: 80
