kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gcp-cluster
nodes:
  - role: control-plane
    labels:
      cloud: gcp
      region: us-central1
      zone: us-central1-a
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "cloud=gcp,region=us-central1,zone=us-central1-a,instance-type=n1-standard-2"
  - role: worker
    labels:
      cloud: gcp
      region: us-central1
      zone: us-central1-b
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "cloud=gcp,region=us-central1,zone=us-central1-b,instance-type=n1-standard-4"
networking:
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/12"
